spring:
  application:
    name: log-collector-splunk
  threads:
    virtual:
      enabled: true
  # ai:
  #   retry:
  #     max-attempts: 3
  #   openai:
  #     api-key: ${OPENAI_API_KEY:sk-placeholder}
  #     chat:
  #       options:
  #         model: gpt-4o

langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY:demo}
      model-name: gpt-4
      temperature: 0.0

splunk:
  host: ${SPLUNK_HOST:localhost}
  port: ${SPLUNK_PORT:8089}
  username: ${SPLUNK_USERNAME:admin}
  password: ${SPLUNK_PASSWORD:changeme}
